### ISSUE TITLE
Database sorunu

### ISSUE THREAD

**Issue by seymennc** [tayfunerbilen/php-boilerplate#6]
illuminate/database paketini kurmaya çalışırken hata veriyor. 2 gündür her yere baktım ama sonuç alamadım. Yardımcı olabilir misiniz.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires illuminate/database ^9.5 -> satisfiable by illuminate/database[v9.5.0, v9.5.1].
    - illuminate/database[v9.5.0, ..., v9.5.1] require illuminate/collections ^9.0 -> found illuminate/collections[v9.0.0, ..., v9.5.1] but the package is fixed to v8.83.5 (lock file version) by a partial update and that version doe
s not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require illuminate/database:*" to figure out if any version is installable, or "composer require illuminate/database:^2.1" if you know 
which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by borakayalar** [comment]
Seymen merhabalar,
Ben de bu boilerplate üzerinden devam ettim. Benim requirementlarım aşağıdaki gibi versiyon sorunu olabilir.
İstersen aşağıdakilerden senin için gerekli olanları requirementlarına ekleyebilirsin.

  "require": {
    "izniburak/router": "^2.3",
    "jenssegers/blade": "^1.4",
    "vlucas/valitron": "^1.4",
    "filp/whoops": "^2.14",
    "arrilot/dotenv-php": "^2.0",
    "nesbot/carbon": "^2.53",
    "aura/session": "^2.1",
    "illuminate/database": "^8.61",
    "ext-openssl": "*",
    "ext-json": "*",
    "ext-curl": "*",
    "vimeo/vimeo-api": "^3.0",
    "league/oauth2-google": "^4.0",
    "wisembly/elephant.io": "^3.3",
    "illuminate/pagination": "^8.80",
    "ext-soap": "*"
  },

**Comment by seymennc** [comment]
Teşekkürler sizin kullandığınız sürümü update ettiğimde kurabildim sorunsuzca <3

**Comment by borakayalar** [comment]
Rica ederim. Düzeldiğine sevindim.
